### ISSUE TITLE
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)

### ISSUE THREAD

**Issue by Pawansingh333** [Freddywhest/DotcoinBot#4]
please fix this 
 ❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
❗️Unknown error during Authorization: RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)

**Comment by Freddywhest** [comment]
Your session is expired. Create a new session
