### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by lucasnguyen3979** [Freddywhest/DotcoinBot#6]
At first it runs fine, but after a while of sleeping to wait for the next task it will happen.
I'm using the latest NodeJS LTS version.

![image](https://github.com/user-attachments/assets/a284e521-e587-41ec-845f-599f17f3e2b2)

**Comment by lucasnguyen3979** [comment]
And after sleeping it doesn't automatically start tapping again, I have to stop > start the bot again for it to tap.

**Comment by Freddywhest** [comment]
Restart the bot
