### ISSUE TITLE
3x-4x range

### ISSUE THREAD

**Issue by danazor** [Freddywhest/DotcoinBot#8]
Hello! Does the bot click in a straightforward manner for the given click limit within 30 seconds? Or does it speed up from 1x to 4x and continue clicking between 3x-4x?

**Comment by Color-maN** [comment]
> Здравствуйте! Выполняет ли бот последовательные клики в течение 30 секунд? Или он ускоряется с 1 до 4 раз и продолжает кликать с 3 до 4 раз?

Можете об этом не задумываться. Это механика работает только на стороне пользователя на его устройстве. Сервер получает только общее количество кликов. Так что все сделано как надо.

Можете закрыть данную проблему.
